# Generated by Django 4.0 on 2022-01-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='blog_description',
            field=models.TextField(),
        ),
    ]
