# Generated by Django 4.0 on 2022-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_project_image_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='href_str',
            field=models.CharField(default='{%%}',max_length=100),
            preserve_default=False,
        ),
    ]
