# Generated by Django 4.0 on 2022-01-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_href_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='href',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
