# Generated by Django 4.0 on 2022-01-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='href_str',
        ),
        migrations.AlterField(
            model_name='project',
            name='href',
            field=models.CharField(max_length=100),
        ),
    ]
