# Generated by Django 4.0 on 2022-01-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_href_str_alter_project_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='href',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
